server:
  port: 8010

spring:
  application:
    name: DiscoveryService

#Eureka Standalone Server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/