server:
  port: 0

spring:
  application:
    name: users-ws

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  devtools:
    restart:
      enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: update

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1 #1은 모든 요구가 다 된다라는 뜻

#  datasource:
#    url: jdbc:h2:mem:testdb

eureka:
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:8010/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
gateway:
  ip: 59.29.224.68

logging:
  level:
    come.example.photoappapiusers.client: DEBUG

feign:
  hystrix:
    enabled: true

albums:
  url: http://albums-ws/users/%s/albums
  exception:
    albums-not-found: Users albums are not found

#token:
#  expiration_time: 864000000 # 10days (milliseconds)
#  secret: local_secret

#login:
#  url:
#    path: /users/login