server:
  port: 8012

spring:
  application:
    name: ConfigServer

  profiles:
    active: native

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ry7791/MyAppConfiguration.git
          username:
          password:
          clone-on-start: true
        native:
          search-locations: file:///${user.home}/Work/springCloudDev

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh