login:
    url:
      path: /users/login

spring:
    datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBIZEy8dSzuV87v/OyIlsZMWmkNoB2YPB3iQx7/kkeDv6ruefVVXjKm2zLjCjI2uvjezFIJigNkjqgZz1cE58kiGVO9ivNJdzpGl65+nCiueaR8aTKSxdbXt6JBaqV+w/HjeyangdeVvwd8x3JnZ7ARRNZkO+DDEyFe9UYW9QdSv1RgIoi4PWEk2XjgbYWU2pr1+zwIab4dqJdFBBOvOlapRED0LS0lKivu0jd+l7H52/ox5A6oSrU6I9RPUnQOW27ssjuCo/N+JHr/THeZPsiGIvSu/iZM/a5motK48inYf3PFlLAkyu7/dJlO/hbyKaupTFoMsYyXNe2UPhHZHbMwGyi/VEEAmUYKXdS2brU0trxAoiNg9soLw667p2kecjM='