server:
  port: 8011

spring:
  application:
    name: ZuulServer

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/


api:
  h2console:
    url:
      path: /users-ws/h2-console/**

  login:
    url:
      path: /users-ws/users/login

  registration:
    url:
      path: /users-ws/users

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

token:
  secret: local_secret
